### ISSUE TITLE
After upgrade to Windows 11, Scanning isn't working from http

### ISSUE THREAD

**Issue by Lisra-git** [taburineagle/NeewerLite-Python#44]
Hello,
after upgrade to Windows 11, scan from http server got huge difficulty to complete, here is log from CMD : 

```
  loop = asyncio.get_event_loop() # get the current asyncio loop
[16:54:42] - Starting program with command-line arguments
[16:54:42] - Starting the HTTP Server on Port 8080...
[16:54:42] - -------------------------------------------------------------------------------------
127.0.0.1 - - [05/Aug/2022 16:54:53] "GET /NeewerLite-Python/doAction?discover HTTP/1.1" 200 -
[16:54:53] - Processing HTTP arguments
[16:54:53] - Searching for new lights
[16:54:58] - Found new light! [NEEWER-RGB660] MAC Address: Redacted RSSI: -87 dBm
[16:54:58] - Found new light! [NEEWER-RGB660] MAC Address: Redacted  RSSI: -88 dBm
[16:54:58] - Found new light! [NEEWER-RGB660] MAC Address:  Redacted  RSSI: -87 dBm
[16:54:58] - Found new light! [NEEWER-RGB660] MAC Address: Redacted RSSI: -80 dBm
[16:54:58] - Found new light! [NEEWER-RGB660] MAC Address: Redacted  RSSI: -87 dBm
[16:54:58] - Attempting to link to light [NEEWER-RGB660] MAC Address: Redacted  (Attempt 1 of 6)
[16:54:58] - Attempting to link to light [NEEWER-RGB660] MAC Address: Redacted  (Attempt 1 of 6)
[16:54:58] - Attempting to link to light [NEEWER-RGB660] MAC Address: Redacted  (Attempt 1 of 6)
[16:54:58] - Attempting to link to light [NEEWER-RGB660] MAC Address: Redacted  (Attempt 1 of 6)
[16:54:58] - Attempting to link to light [NEEWER-RGB660] MAC Address: Redacted  (Attempt 1 of 6)
Exception in thread htmlProcessThread:
Traceback (most recent call last):
  File "C:\Users\Redacted \Downloads\NeewerLite-Python-0.12\NeewerLite-Python-0.12\NeewerLite-Python.py", line 2276, in connectToLight
    isConnected = await availableLights[returnLightIndexesFromMacAddress(lightMAC)[0]][1].connect() # try connecting it (and return the connection status)
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 314, in connect
    await self.get_services()
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 506, in get_services
    await self._requester.get_gatt_services_async(*args),
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Redacted\Downloads\NeewerLite-Python-0.12\NeewerLite-Python-0.12\NeewerLite-Python.py", line 2634, in parallelAction
    await asyncio.gather(*parallelFuncs) # run the functions in parallel
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Redacted\Downloads\NeewerLite-Python-0.12\NeewerLite-Python-0.12\NeewerLite-Python.py", line 2811, in processHTMLCommands
    loop.run_until_complete(parallelAction("connect", [-1], False)) # try to connect to *all* lights in parallel
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
```

Thanks for any help

**Comment by taburineagle** [comment]
Hi @Lisra-git - sorry for the delay in responding!  I'm not 100% sure what's going on here, it looks like an asyncio CancelledError issue, but I'm not sure _why_ it's cancelling - maybe it was the upgrade to Windows 11 that did that (possibly Bleak has an issue where it's not yet compatible with Win11?)  It definitely looks like it's partially working, as it's getting the light information on boot.  I don't have a Windows 11 install to test myself, but I could get a virtual machine setup going to check how it handles NeewerLite-Python.  Have you tried running the GUI version (just launching it directly in Windows) and seeing if you get the same error?

**Comment by Lisra-git** [comment]
Hey
Thanks for replying
Actually I tried the GUI and Scan operation crash too
Sometime by rebooting the program and launching the scan again it will be successful but it's just a pain to do.

**Comment by taburineagle** [comment]
That's interesting - do you get the same kind of error with the GUI then?  The asyncio.CancelledError?  It looks like it's getting hung up on the connection phase - it scans for the lights fine, but when it goes to connect to them, it runs into an issue.  I will say, the RSSI level on those lights are pretty weak (~-80dBm), so it might have issues connecting to them due to that.  Although if Windows 10 worked fine all the time, it might be something else.

**Comment by Lisra-git** [comment]
Yes exact same error
Did rollback to Win10 due to that and all work perfect like before

**Comment by taburineagle** [comment]
_Huh_ - that's so odd!  I'm curious what's causing that now.

**Comment by taburineagle** [comment]
I'm going to close this for now @Lisra-git - I would like to get either a Win11 install or VM and test this out more in the future, but that's not quite on my plate at the moment... I'll let you know what happens when I get to that!
