### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'get_running_loop'

### ISSUE THREAD

**Issue by mungewell** [taburineagle/NeewerLite-Python#68]
When attempting to run I got the following error
```
$ python3 NeewerLite-Python.py 
---------------------------------------------------------
             NeewerLite-Python ver. 0.13
                 by Zach Glenwright
  > https://github.com/taburineagle/NeewerLite-Python <
---------------------------------------------------------
Traceback (most recent call last):
  File "NeewerLite-Python.py", line 3338, in <module>
    setUpAsyncio() # set up the asyncio loop
  File "NeewerLite-Python.py", line 1582, in setUpAsyncio
    asyncioEventLoop = asyncio.get_running_loop()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'
```

It seams from another project/bug, that Syncio had a change:
https://github.com/dask/distributed/issues/3381

Seems that get_running_loop was added in 3.7: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop

And I am running (xubuntu) with:
```
$ python3 
Python 3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
```

Following the bug I was able to (hackily) patch Neewer to work with:
```
$ git diff
diff --git a/NeewerLite-Python.py b/NeewerLite-Python.py
index 22a29ea..339ebcd 100644
--- a/NeewerLite-Python.py
+++ b/NeewerLite-Python.py
@@ -28,6 +28,11 @@ import time
 
 from datetime import datetime
 
+if sys.version_info[:2] >= (3, 7):
+    from asyncio import get_running_loop
+else:
+    from asyncio import _get_running_loop as get_running_loop
+
 # IMPORT BLEAK (this is the library that allows the program to communicate with the lights) - THIS IS NECESSARY!
 try:
     from bleak import BleakScanner, BleakClient
@@ -1579,7 +1584,7 @@ def setUpAsyncio():
     global asyncioEventLoop
 
     try:
-        asyncioEventLoop = asyncio.get_running_loop()
+        asyncioEventLoop = get_running_loop()
     except RuntimeError:
         asyncioEventLoop = asyncio.new_event_loop()
```

Maybe this could for the basis of a proper/clean fix. Thanks.

**Comment by taburineagle** [comment]
Thanks for writing @mungewell - ahh, I thought I had fixed that problem a few versions back, but I use a different version of Python/asyncio, so it's good to know about that.  I'll check into that!

**Comment by mungewell** [comment]
Maybe I was a bit premature in saying that it's working, it gets further but it complains that a process is already running.

If I force "new_event_loop()" instead, it scans for Lights (on CLI - I don't particularly want to install QT). I'm still waiting for lights to ship to me, so will report again when they arrive.

**Comment by taburineagle** [comment]
Hmm, when you say another process, do you mean the "Another instance of NeewerLite-Python is running" message shows, or asyncio complains about another event process running?

**Comment by mungewell** [comment]
Yes, it was reporting that another process is already running.... however I changed my patch to
```
diff --git a/NeewerLite-Python.py b/NeewerLite-Python.py
index 22a29ea..0bc5eaf 100644
--- a/NeewerLite-Python.py
+++ b/NeewerLite-Python.py
@@ -1582,6 +1582,8 @@ def setUpAsyncio():
         asyncioEventLoop = asyncio.get_running_loop()
     except RuntimeError:
         asyncioEventLoop = asyncio.new_event_loop()
+    except AttributeError:
+        asyncioEventLoop = asyncio.new_event_loop()
 
     asyncio.set_event_loop(asyncioEventLoop)
```
and it seems to be working OK. I can `--list` and control my light(s).
```
$ python3 NeewerLite-Python.py --cli --light='F2:F6:67:12:35:1B' --off           
---------------------------------------------------------
             NeewerLite-Python ver. 0.13
                 by Zach Glenwright
  > https://github.com/taburineagle/NeewerLite-Python <
---------------------------------------------------------
[19:44:00] - Starting program with command-line arguments
[19:44:00] -  > Launch GUI: False
[19:44:00] -  > Show Debug Strings on Console: True
[19:44:00] -  > Mode: OFF
[19:44:00] - -------------------------------------------------------------------------------------
[19:44:00] -  > CLI >> MAC Address of light to send command to: F2:F6:67:12:35:1B
[19:44:00] -  > CLI >> Bytestring to send to light: 0x78 0x81 0x1 0x2 0xfc
[19:44:00] - -------------------------------------------------------------------------------------
[19:44:00] -  > CLI >> Attempting to connect to light (attempt 1 of 6)
[19:44:00] - -------------------------------------------------------------------------------------
[19:44:00] - Attempting to link to light [NEEWER-RGB176] MAC Address: F2:F6:67:12:35:1B (Attempt 1 of 6)
[19:44:02] - Successful link on light [NEEWER-RGB176] MAC Address: F2:F6:67:12:35:1B
[19:44:02] - -------------------------------------------------------------------------------------
[19:44:02] -  > CLI >> Attempting to write to light (attempt 1 of 6)
[19:44:02] - -------------------------------------------------------------------------------------
[19:44:02] - Going into send mode
[19:44:02] - -------------------------------------------------------------------------------------
[19:44:02] -  > CLI >> Attempting to disconnect from light (attempt 1 of 6)
[19:44:02] - -------------------------------------------------------------------------------------
[19:44:04] - Successfully unlinked from light 1 [NEEWER-RGB176] MAC Address: F2:F6:67:12:35:1B
```
