### ISSUE TITLE
Scanning crashes sometimes

### ISSUE THREAD

**Issue by danir-de** [taburineagle/NeewerLite-Python#76]
When scanning for new lights, while trying to connect to a light, the scanning process crashes with the following error message:

```
[17:46:26] - Searching for new lights
[17:46:31] - Matching whitelisted address found - MAC Address: C0:26:BC:3D:80:E0, adding to the list
[17:46:31] - Matching whitelisted address found - MAC Address: DD:B4:5B:5D:42:37, adding to the list
[17:46:31] - Light found! [NW-20210034&00000000] MAC Address: C0:26:BC:3D:80:E0 but it's already in the list.  It may have disconnected, so relinking might be necessary.
/home/danir/Software/Neewer/./NeewerLite-Python.py:2159: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead
  availableLights[b][0].rssi = currentScan[a].rssi # update the RSSI information
Exception in thread workerThread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/danir/Software/Neewer/./NeewerLite-Python.py", line 2600, in workerThread
    threadAction = _loop.run_until_complete(findDevices()) # add new lights to the main array
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/danir/Software/Neewer/./NeewerLite-Python.py", line 2159, in findDevices
    availableLights[b][0].rssi = currentScan[a].rssi # update the RSSI information
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'rssi' of 'BLEDevice' object has no setter

```

**Comment by taburineagle** [comment]
This is definitely a Bleak issue (the Bluetooth control library).  Apologies for those, Bleak has updated their procedure for getting RSSI information (the signal level) since the version I originally coded against, and I need to sit down and figure out the best way to update my coding to reflect their changes.

**Comment by taburineagle** [comment]
OK, @danir-de  - in the latest commit, I have changed the way I ask Bleak to detect devices to match the latest version of Bleak's way of delivering information, so this _should_ alleviate this specific issue (and the "BLEDevice.rssi" and "AdvertisementData.rssi" deprecation warnings) - NeewerLite-Python will still not control a MS60B light _yet_, until I get my hands on one to test out how they send commands back through the app.

**Comment by taburineagle** [comment]
I'm going to close this one - if you have any issues with the BLEDevice.rssi or AdvertisementData.rssi, please feel free to re-open it!
