### ISSUE TITLE
UPDATES... kind of 🐜

### ISSUE THREAD

**Issue by taburineagle** [taburineagle/NeewerLite-Python#88]
Hello!  It has been a _long_ time since I've been here, and the reason is... wait for it... **ants** - 

Or, to be more specific, necessity to work on other projects _because_ of ants.  A camera enclosure I've been running had an ant infestation that not only destroyed the hardware I designed inside of the enclosure, but also destroyed the **camera** somehow - to the point where a fully-functional 4K camera can no longer record in 4K because of... _reasons_ - it sees the 4K shot, it sets it up like normal, but refuses to write data for 4K (HD is fine however)... so I'm guessing something inside the memory of the camera (the buffer perhaps) is shot.  Due to that, I've spent the last few months working on a completely new system (both engineering completely new hardware, software and layout logistics) that has kind of become a white whale of a project - one that I have needed to see through to the end.  I've done it, designed an entirely new PCB, written an entirely new (and much better, honestly) daemon in C, etc. - but it's taken 2 months of complete focus that has taken me away from other projects like NeewerLite-Python.  One _plus-side_ to that is I've had the chance to code with an ESP32, and see the kinds of things it can do (originally I had a cobbled together PCB that I designed running a ATTiny chip connected to a Pi Zero, I simplified the entire thing using just an ESP32) - so I might actually be able to port a version of NeewerLite-Python (it wouldn't be _Python_ any more, but meh) to an ESP32 using the built-in WiFi and Bluetooth, which I _think_ was a vision @fribse had years ago for a project like that based on a microcontroller instead of a PC.

Ha, tl;dr - I'm still here.  Haphazard, but here 😊

**Comment by taburineagle** [comment]
Here's a picture of the new board, if anyone's interested ~

![2024-05-26_21-08-21](https://github.com/user-attachments/assets/afbcc67f-3c8d-4dff-8a50-28f7f9b863cd)

**Comment by fribse** [comment]
Hey @taburineagle 
That sounds very interesting. Yes, my though was just that as I know it the CPU usage is miniscule, so something like micropython might be able to do the trick?
Glad that you got your project on the way.

Btw. did implement any of those 'busy' signs in the files for the webbased? I was contemplating looking into updating it, if something new has appeared.

**Comment by taburineagle** [comment]
@fribse - I'll have to check into MicroPython!  I've actually never used that variant, but it looks interesting.  C would still work, I'm guessing - semantically, I'd just have to change the name for the ESP version to something else, as just "NeewerLite" has already been taken 😄  ESP-NLP... or something...

I have actually added that in a while back - it might have gotten lost in the fray of updates - [I pushed a busy signal update in the latest commit to the WIP-HTTP-Server-Mods branch...](https://github.com/taburineagle/NeewerLite-Python/commit/963918bf07a147956c42bc00a961977a4c06a49d)

**Comment by fribse** [comment]
Ha ha, uh, the big change in naming.
Ahh, now I found it, ok, I'll try and fetch that and update the two files :-)
Thankyou!

**Comment by fribse** [comment]
I just tried the 'new' version, but I get a list "index out of range" when I replace the two files.
I tried moving the 'light_prefs' content to a backup folder, but that didn't help.

```
Jul 20 18:15:51 neewerlitepi systemd[1]: Started Run NeewerLite-Python HTTP Daemon as a service.
Jul 20 18:15:54 neewerlitepi python3[573]: Traceback (most recent call last):
Jul 20 18:15:54 neewerlitepi python3[573]:   File "/opt/NeewerLite-Python/NeewerLite-Python.py", line 3897, in <module>
Jul 20 18:15:54 neewerlitepi python3[573]:     loadCustomPresets() # if there's a custom mapping for presets, then load that into memory
Jul 20 18:15:54 neewerlitepi python3[573]:   File "/opt/NeewerLite-Python/NeewerLite-Python.py", line 1976, in loadCustomPresets
Jul 20 18:15:54 neewerlitepi python3[573]:     if currentParams[1] == 120: # we have a new-style list of parameters, so copy them as-is
Jul 20 18:15:54 neewerlitepi python3[573]: IndexError: list index out of range

```

**Comment by taburineagle** [comment]
Hmm, interesting... are you still using the older custom preset file structure?  The one from #81?  When I tested it with the old-to-new style converter, everything worked here on my end, but there may have been an eccentricity I didn't notice.  Are you saying if you have no `light_prefs` folder in the NeewerLite-Python folder, it still presents that error?

**Comment by fribse** [comment]
I just emptied the light_prefs folder.
I tried removing it entirely now, and now it starts.
I've asked it to scan for lights, and now it shows this:
![billede](https://github.com/user-attachments/assets/0cd40f29-12e0-4a57-9c28-9c965bab285a)
However, it doesn't exit, and I can't trigger anything?
If I do a restart of the service, it restarts, and then stops again a second later

**Comment by taburineagle** [comment]
Looking at that screenshot, it looks like it just successfully connected to CE:D9:49:A3:1F:F7 (it shows this at the top), but the table still shows lights aren't completely linked yet.  

![image](https://github.com/user-attachments/assets/56c00c84-b36e-4932-ac9f-4e01d4bc1b83)

Are you saying if you let it look for lights and link them, the message at the top doesn't go away if you let it run for a longer period? (the HTTP Server busy message just shows the last message received from the program when it's busy, so in the screenshot above, it's still working on connecting to the lights and isn't 100% ready for anything else yet)...
